### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [frankjoke/ioBroker.statemachine#2]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/frankjoke/ioBroker.statemachine

- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E115] No license found in io-package.json
- [ ] [E120] Unknown type found in io-package.json
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.statemachine"
- [ ] [E504] found setInterval in "statemachine.js, but no clearInterval detected
- [ ] [E301] Tests on Travis-ci.org are broken. Please fix.
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/frankjoke/ioBroker.statemachine", press the settings button beside the about title and add some topics.
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2022 frankjoke <frankjoke@hotmail.com>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 frankjoke <frankjoke@hotmail.com>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode
- [ ] [W400] Cannot find "statemachine" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by frankjoke** [comment]
statemachine is in very early state, I did not announce it even for beta test, I use git there only to test it on my different test systems. I will work on it after Easter only, It will need to re-write interface completely to be able to add 1-2 functionalities planned.

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
